<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<meta http-equiv="Expires" CONTENT="0"/>
<meta http-equiv="Cache-Control" CONTENT="no-cache"/>
<meta http-equiv="Pragma" CONTENT="no-cache"/> 
<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />

<link rel="stylesheet" type="text/css" href="/style/common.css?v=20150905" />
<link rel="stylesheet" type="text/css" href="/style/boxy.css?v=20150905" />
